### PR TITLE
Bookclub

### PR DESCRIPTION
**Pull request by layzrd**
> Book Library module
- add create a book feature
- add display books feature
- add delete a book feature
- add change reading status feature

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @abredi and @muhenge, great job on this project :+1: The main functionality of the project works well :100: Kindly address the comment below: :smile: 

- Our project is lacking a very important component, which is the Pull Request lacking a title and a short summary of the project :slightly_smiling_face: 

[Optional]
- Let us improve our styling
- Let us implement persisting data in localStorage, [link](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API)

Once this is fixed, kindly submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @abredi and @muhenge, great job on this project :+1: Having refactored the code to separate `dom` from `logic` :fireworks: However I hereby can not add a book. Kindly check the screenshot below so we can fix the problem :slightly_smiling_face: 
- `Firebase` error
fb

We can submit another code review once this is fixed, and we can submit or add a book :100: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by layzrd** [comment]
Hello @addod19, Thanks for your review. To install the project on your machine, please follow the installation guide from the Readme file but, if you want only to add, remove, and set the read status of a book, you can use the live link.

**Comment by addod19** [comment]
> Hello @addod19, Thanks for your review. To install the project on your machine, please follow the installation guide from the Readme file but, if you want only to add, remove, and set the read status of a book, you can use the live link.

Yes @abredi, sorry about that. Could you send another code review? I saw a commit message "remove firebaserc" which is why. Kindly submit another code review so I can fix this. Thank you

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi @abredi and @muhenge, congratulations on this project :+1: The code works as expected :100: Live link works perfectly :+1: 

Go ahead and continue with your next projects :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Pull request merged**
